name: Tests - Go

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  go-tests:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: ./.github/actions/setup-tools

      - name: Ensure frontend/dist directory exists and is embeddable
        shell: bash
        run: mkdir -p frontend/dist && touch frontend/dist/.gitignore

      - name: Run Go tests
        shell: bash
        run: |
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v5
      #   with:
      #     slug: AdbAutoPlayer/AdbAutoPlayer
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     flags: ${{ matrix.os }}
      #     files: "coverage.txt"
      #     disable_search: 'true'
