name: Run - pre-commit
permissions:
  contents: read
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  pre-commit:
    name: pre-commit hooks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get -yq update
          sudo apt-get -yq install libgtk-3-0 libwebkit2gtk-4.1-dev gcc-aarch64-linux-gnu

      - name: Setup Go, Wails, Node
        uses: ./.github/actions/setup-tools

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.7.11
          enable-cache: true

      # for Frontend checks
      - name: npm install
        run: |
          cd frontend
          npm install

      - name: Wails3 build
        run: wails3 task build

      - run: uvx pre-commit run --all-files
